### ISSUE TITLE
Help testing?

### ISSUE THREAD

**Issue by mydogisjibe** [mydogisjibe/SuggestApp#40]
I'm having trouble getting my program to work. It should make a request to google, and let me know if it worked. I have a feeling it could be because I'm using an emulator. Would someone with an android test it out for me? Thanks!!!

**Comment by xeonjake** [comment]
i cant test the login page, it crashed which i tries to start it. suspected cause line 30 in DatabaseConnection.java

full error dump:

03-30 21:38:38.759  12358-12358/piratecrew.suggestapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: piratecrew.suggestapp, PID: 12358
    java.lang.RuntimeException: Unable to start activity ComponentInfo{piratecrew.suggestapp/piratecrew.suggestapp.LoginActivity}: android.os.NetworkOnMainThreadException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2248)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:212)
            at android.app.ActivityThread.main(ActivityThread.java:5151)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1154)
            at java.net.InetAddress.lookupHostByName(InetAddress.java:385)
            at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
            at java.net.InetAddress.getAllByName(InetAddress.java:214)
            at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
            at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
            at java.net.InetAddress.getAllByName(Native Method)
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:141)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
            at piratecrew.suggestapp.DatabaseConnection.<init>(DatabaseConnection.java:30)
            at piratecrew.suggestapp.LoginActivity.onCreate(LoginActivity.java:33)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:212)
            at android.app.ActivityThread.main(ActivityThread.java:5151)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mydogisjibe** [comment]
That's the same problem I'm having. Do you know anything about making site requests? I'll look into it some more.

**Comment by NSagan271** [comment]
I'm not sure if this will be any help, but it worked when I added a block saying:
catch(RuntimeException e){
            e.printStackTrace();
        }
I'm hoping that this narrows down the possible errors that could have occurred.

**Comment by mydogisjibe** [comment]
Ok, I've now confirmed that it is the program, not the emulator, since I was able to use the web browsing app on it.

**Comment by mydogisjibe** [comment]
@NSagan271  I think your on to something. The program went through the catch(RuntimeExeption), but I cant find where printStackTrace(); prints the error.

**Comment by mydogisjibe** [comment]
Its still complaining about that one line. Does anyone know better ways of making a GET statement? or even a POST? None of the examples I've seen on the internet have been much help.

**Comment by NSagan271** [comment]
Prints to LogCat:
catch(RuntimeException e){
            e.printStackTrace();
            stackTrace = Log.getStackTraceString(e);
            Log.d("Login Problem", stackTrace);
        }
